function tests = test_repository_layout
tests = functiontests(localfunctions);
end

function testRequiredFiles(testCase)
root = fileparts(fileparts(mfilename('fullpath')));
required = { ...
    'Voltage.m', ...
    'buildTrialTableSLAP2.m', ...
    fullfile('source_extraction','computeVoltageF0.m'), ...
    fullfile('source_extraction','computeVoltageDFF.m'), ...
    fullfile('dependencies','io','loadStructFromH5.m'), ...
    fullfile('dependencies','io','saveStructToH5.m'), ...
    fullfile('dependencies','gui','setParams.m'), ...
    fullfile('dependencies','gui','optionsGUI.m')};
for k = 1:numel(required)
    verifyEqual(testCase,exist(fullfile(root,required{k}),'file'),2,required{k});
end
end
